services:
  - type: web
    name: bfp-laravel-api
    env: php
    plan: free
    region: singapore
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      npm install
      npm run build
    startCommand: |
      php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:ruUEhu2+gyhDTXV3/q2jnLEgdnGWL71ZTalYG92nTr4=
      - key: APP_URL
        value: https://bfpsystem.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d46no4re5dus73dfu250-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: bfp_system
      - key: DB_USERNAME
        value: bfp_user
      - key: DB_PASSWORD
        value: uPmXD3tdqs2wHwdupNlibBjLdzgvuE3z
